import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/docs/logo.png',
    apple: '/docs/logo.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/remixicon@4.6.0/fonts/remixicon.css"
        />
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function () {
                try {
                  var theme = localStorage.getItem('theme');
                  var prefersDark = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;
                  var isDark = theme === 'dark' || (!theme || theme === 'system') && prefersDark;
                  var root = document.documentElement;
                  if (isDark) root.classList.add('dark');
                  else root.classList.remove('dark');

                  var varsRaw = localStorage.getItem('sf_theme_vars_v1');
                  if (varsRaw) {
                    var vars = JSON.parse(varsRaw);
                    if (vars && typeof vars === 'object') {
                      for (var key in vars) {
                        if (!Object.prototype.hasOwnProperty.call(vars, key)) continue;
                        if (typeof key !== 'string' || key.indexOf('--sf-') !== 0) continue;
                        var value = vars[key];
                        if (typeof value !== 'string') continue;
                        root.style.setProperty(key, value);
                      }
                    }
                  }
                } catch (e) {}
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
